config/routes.rb
SiliconGroningen::Application.routes.draw do
  root to: 'home#show'
  devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }
  match '/account/profile/new' => 'people#new', :as => 'account_new_profile'

  localized do
    resources :companies
    resources :people
    resources :initiatives
  end

  namespace :admin do
    root to: 'dashboard#show'
    resources :accounts
    resources :jobs
    resources :people do
      resources :companies
      resources :initiatives
    end
    resources :initiatives do
      resources :people
    end
    resources :companies do
      resources :jobs
      resources :people
    end
  end

end

app/views/layouts/admin/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    =airbrake_javascript_notifier
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "grunn.io > admin area"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "admin/application", :media => "all"
    / %link(href="images/favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=admin_root_path) grunn.io | Admin
          .container.nav-collapse
            %ul.nav
              %li= link_to I18n.t('navigation.companies'), admin_companies_path
              %li= link_to I18n.t('navigation.initiatives'), admin_initiatives_path
              %li= link_to I18n.t('navigation.persons'), admin_people_path
              %li= link_to I18n.t('navigation.jobs'), admin_jobs_path
            %ul.nav.pull-right
              -if account_signed_in? && current_account.is_admin?
                %li= link_to('sign out', destroy_account_session_path, :method => :delete)
              -else
                %li= link_to('sign in', new_account_session_path)

    =render 'shared/alerts'
    =render 'admin/shared/breadcrumbs'

    .container
      .row
        =yield :main

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"