config/routes.rb
SiliconGroningen::Application.routes.draw do
  root to: 'home#show'
  devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }
  match '/account/profile/new' => 'people#new', :as => 'account_new_profile'

  localized do
    resources :companies
    resources :people
    resources :initiatives
  end

  namespace :admin do
    root to: 'dashboard#show'
    resources :accounts
    resources :jobs
    resources :people do
      resources :companies
      resources :initiatives
    end
    resources :initiatives do
      resources :people
    end
    resources :companies do
      resources :jobs
      resources :people
    end
  end

end

app/views/shared/_alerts.html.haml
-if notice
  %div.alert.alert-info.fade.in
    = link_to('x', '#', data: {dismiss: "alert"}, class: 'close')
    %p= notice

-if alert
  %div.alert.alert-error.fade.in
    = link_to('x', '#', data: {dismiss: "alert"}, class: 'close')
    %p= alert

app/views/shared/_factsheet_actions.haml
.actions
  - if current_account.try(:can_update?, resource)
    = link_to edit_resource_path(resource), class: 'btn tiny', title: 'aanpassen' do
      %i.sweets-edit
      aanpassen
  - if (current_account.try(:can_delete?, resource) && resource.class != Person)
    = link_to resource, title: 'verwijderen', :confirm => 'weet je het zeker?', :method => :delete, class: 'btn tiny alert' do
      %i.sweets-delete

app/views/shared/_header.html.haml
%header.whole
  .logo.frontpage
    =link_to(root_path) do
      =image_tag('logo.png')
  .introduction
    %p Grunn.io is de open database met technologiebedrijven, mensen en initiatieven uit het technologisch innovatieve Groningen.
  %hr
  %nav
    %ul
      %li= link_to "bedrijven", companies_path
      %li= link_to "personen", people_path
      %li= link_to "initiatieven", initiatives_path
      %li= link_to "over", "/initiatieven/grunn-io"

app/views/shared/_header_compact.html.haml
%header.whole.compact
  .logo.compact
    =link_to(root_path) do
      =image_tag('logo.png')
  %nav
    %ul
      =nav_to "bedrijven", companies_path
      =nav_to "personen", people_path
      =nav_to "initiatieven", initiatives_path
      =nav_to "over", "/initiatieven/grunn-io"

app/views/shared/_login_bar.html.haml
.login-bar.whole.text-right
  %ul.steps
    - if account_signed_in? && current_account.is_admin?
      %li
        = link_to(admin_root_path) do
          %i.icon-admin
          %span.text admin
      %li
        = link_to(destroy_account_session_path, :method => :delete) do
          %i.icon-signout
          %span.text afmelden
    -elsif account_signed_in?
      %li
        %i.sweets-person
        = "#{current_account.email}"
      %li
        -if current_account.person.published
          = link_to(edit_person_path(current_account.person), class: 'green') do
            %i.sweets-check-mark
            profiel gepubliceerd
        - else
          = link_to(edit_person_path(current_account.person), class: 'red') do
            %i.sweets-delete
            profiel niet gepubliceerd
      %li
        = link_to(destroy_account_session_path, :method => :delete) do
          %i.icon-signout
          %span.text afmelden
    - else
      Aanmelden/Inloggen met:
      %li
        = link_to(account_omniauth_authorize_path(:facebook), title: "Facebook") do
          %i.icon-facebook
          / %span.text Facebook
      %li
        = link_to(account_omniauth_authorize_path(:github), title: "Github") do
          %i.icon-github
          / %span.text Github
      %li
        = link_to(account_omniauth_authorize_path(:linkedin), title: "Linkedin")do
          %i.icon-linkedin
          / %span.text Linkedin
      %li
        = link_to(new_account_session_path, title: "Grunn.io account") do
          %i.icon-envelope
          // %span.text Grunn.io

app/views/shared/_navbar.html.haml
%nav.whole
  %ul
    = nav_link "bedrijven", companies_path
    = nav_link "personen", people_path
    = nav_link "initiatieven", initiatives_path

app/views/shared/_sidebar.html.haml
%section.sidebar.fourth.paperpile
  %i.sweets-info.sweets-large
  %p= raw "Grunn.io is de open database met technologiebedrijven als #{c = Company.all.sample; link_to(c.name, company_path(c))}, specialisten als #{p = Person.all.sample; link_to(p.name, person_path(p))} en initiatieven als #{p = Initiative.all.sample; link_to(p.name, person_path(p))} uit het technologisch innovatieve Groningen."

app/views/shared/_taiga-alerts.html.haml
-if notice
  %ul.messages.success.fade.in
    %li.success
      = link_to('x', '#', data: {dismiss: "alert"}, class: 'close')
      = notice

-if alert
  %ul.messages.alert.fade.in
    %li.alert
      = link_to('x', '#', data: {dismiss: "alert"}, class: 'close')
      = alert