config/routes.rb
SiliconGroningen::Application.routes.draw do
  root to: 'home#show'
  devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }
  match '/account/profile/new' => 'people#new', :as => 'account_new_profile'

  localized do
    resources :companies
    resources :people
    resources :initiatives
  end

  namespace :admin do
    root to: 'dashboard#show'
    resources :accounts
    resources :jobs
    resources :people do
      resources :companies
      resources :initiatives
    end
    resources :initiatives do
      resources :people
    end
    resources :companies do
      resources :jobs
      resources :people
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @companies = Company.published
    @people = Person.published
    @initiatives = Initiative.published
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.haml
%p#notice= notice

-content_for :topbar do
  = render 'shared/login_bar'

-content_for :header do
  = render 'shared/header'

-content_for :main do
  %section.whole.paperpile.bedrijven
    .third
      .title.one
        %i.sweets-lab.sweets-large
        %h2{title: 'Bedrijven'} Bedrijven
      %p Ontdek wat er in Groningen gevestigd is of voeg jouw eigen Groningse onderneming toe.
      = link_to new_company_path, class: 'btn large' do
        %i.sweets-plus
        Toevoegen
    .third
      .title.two
        %i.icon-share-alt.blue-icon.left
        %h3 Recent toegevoegd
        %ul
          -@companies.last(3).each do |c|
            %li
              = link_to(c.name, c)
              %span.specialities= c.specialities.try(:join, ', ')
    .third
      .title.three
        %i.icon-random.blue-icon.left
        %h3 Willekeurige bedrijven
        %ul
          -@companies.sample(3).each do |c|
            %li
              = link_to(c.name, c)
              %span.specialities= c.specialities.try(:join, ', ')
      =link_to "Alle bedrijven...", companies_path, class: "right"

  %section.whole.paperpile.personen
    .third
      .title.one
        %i.sweets-people.sweets-large
        %h2{title: 'Personen'} Personen
      %p Vindt Groningse ondernemers en oprichters of voeg jezelf toe aan de database.
      - if account_signed_in?
        = link_to edit_person_path(current_account.person), class: 'btn large' do
          %i.sweets-edit
          Werk je profiel bij
      - else
        =link_to new_account_registration_path, class: 'btn large' do
          %i.sweets-plus
          Toevoegen
    .third
      .title.two
        %i.icon-share-alt.blue-icon.left
        %h3 Recent toegevoegd
        %ul
          -@people.last(3).each do |p|
            %li
              = link_to(p.name, p)
              %span.specialities= p.specialities.try(:join, ', ')

    .third
      .title.three
        %i.icon-random.blue-icon.left
        %h3 Willekeurige personen
        %ul
          -@people.sample(3).each do |p|
            %li
              = link_to(p.name, p)
              %span.specialities= p.specialities.try(:join, ', ')
      =link_to "Alle personen...", people_path, class: "right"


  %section.whole.paperpile.initiatieven
    .third
      .title.one
        %i.sweets-heart.sweets-large
        %h2{title: 'Initiatieven'} Initiatieven
      %p Initiatieven: Ontdek welke meetups er in Groningen worden georganiseerd en voeg je eigen initiatief toe.
      = link_to new_initiative_path, class: 'btn large' do
        %i.sweets-plus
        Toevoegen
    .third
      .title.two
        %i.icon-share-alt.blue-icon.left
        %h3 Recent toegevoegd
        %ul
          -@initiatives.last(3).each do |i|
            %li
              = link_to(i.name, i)
              // %span.specialities= p.specialities.try(:join, ', ')
    .third
      .title.three
        %i.icon-random.blue-icon.left
        %h3 Willekeurige initiatieven
        %ul
          -@initiatives.sample(3).each do |i|
            %li
              = link_to(i.name, i)
      =link_to "Alle initiatieven...", initiatives_path, class: "right"