config/routes.rb
SiliconGroningen::Application.routes.draw do
  root to: 'home#show'
  devise_for :accounts, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations" }
  match '/account/profile/new' => 'people#new', :as => 'account_new_profile'

  localized do
    resources :companies
    resources :people
    resources :initiatives
  end

  namespace :admin do
    root to: 'dashboard#show'
    resources :accounts
    resources :jobs
    resources :people do
      resources :companies
      resources :initiatives
    end
    resources :initiatives do
      resources :people
    end
    resources :companies do
      resources :jobs
      resources :people
    end
  end

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :integer
#

class Job < ActiveRecord::Base
  include Authority::Abilities
  resourcify

  attr_accessible :description, :title

  belongs_to :companies
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::ResourceController
  authorize_actions_for Job
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.haml
= simple_form_for([:admin, @job]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/admin/jobs/_index.html.haml
%table.table.table-condensed
  %thead
    %tr
      %th= Job.human_attribute_name(:title)
      %th= Job.human_attribute_name(:description)

  - jobs.each do |job|
    %tr
      %td= link_to job.title, [:admin, job]
      %td= link_to job.description, [:admin, job]
      %td.btn-group
        = link_to admin_job_path(job), class: 'btn btn-mini' do
          %i.icon-zoom-in
        = link_to edit_admin_job_path(job), class: 'btn btn-mini' do
          %i.icon-edit
        = link_to [:admin, job], :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-mini btn-danger' do
          %i.icon-trash

=link_to t('actions.add', model: Job.model_name.human), new_admin_job_path, class: 'btn btn-large'

app/views/admin/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', admin_jobs_path

app/views/admin/jobs/index.html.haml
%h1 Listing jobs

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @jobs.each do |job|
    %tr
      %td= job.title
      %td= job.description
      %td= link_to 'Show', [:admin, job]
      %td= link_to 'Edit', edit_admin_job_path(job)
      %td= link_to 'Destroy', [:admin, job], :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Job', new_admin_job_path

app/views/admin/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', admin_jobs_path

app/views/admin/jobs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @job.title
%p
  %b Description:
  = @job.description

= link_to 'Edit', edit_admin_job_path(@job)
\|
= link_to 'Back', admin_jobs_path